### ISSUE TITLE
Infinite loop using parallel processing under Windows

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#211]
When parallel processes is `True` or `None` under Windows, the code runs in an infinite loop, when `method="API"`.
Only if processes if set to `False` this section of the code section is skipped and the API is running without parallel processing.

https://github.com/OpenEnergyPlatform/open-MaStR/blob/0015e81dc33b94587fd053543be93c411550ec89/open_mastr/soap_api/download.py#L811-L842

**Comment by chrwm** [comment]
Did your commit fix the issue, and can this issue be closed?

**Comment by FlorianK13** [comment]
It is still a bug. I changed the default value to None. With api_processes="max" on Windows, it runs into the infinite loop. I'll have a look if I understand why that is the case.

@chrwm Can you check if api_processes = "max" works on Linux?

**Comment by FlorianK13** [comment]
I think that is the source of the bug:

https://www.pythonforthelab.com/blog/differences-between-multiprocessing-windows-and-linux/

**Comment by FlorianK13** [comment]
The easy way is to check the system of the user and if it is windows or mac, we only allow `api_processes=None`. The hard way is to take a deep dive into multiprocessing. 

I'll try the hard way but I will not spend too much time on it.

**Comment by FlorianK13** [comment]
Pool doesn’t work in interactive interpreter and Python classes. It requires `__main__` module to be importable by the children. (See https://towardsdatascience.com/how-to-use-the-multiprocessing-package-in-python3-a1c808415ec2)

The problem is that on windows and mac, the children open up new Pools. This can only be avoided if the Pool is created in a `__name__ == "__main__"` environment. This is not possible in a class method, because the class method never fulfills `__name__ == "__main__"`.

I would therefore argue to use the easy way and only allow parallel processing on Linux.

**Comment by chrwm** [comment]
> Can you check if api_processes = "max" works on Linux?

Yes, it works with my Ubuntu distribution.

> I would therefore argue to use the easy way and only allow parallel processing on Linux.

I'm fine with that!

**Comment by FlorianK13** [comment]
Here is another resource: https://stackoverflow.com/questions/37737085/is-it-possible-to-use-multiprocessing-in-a-module-with-windows

I'll add a check in the code to only allow `api_processes='max'` on Linux.

**Comment by FlorianK13** [comment]
@chrwm Can you check if `api_processes='max'` still works on Linux? On windows, it raises an error now.

**Comment by chrwm** [comment]
@FlorianK13 yes, it still works fine, without problems.

**Comment by FlorianK13** [comment]
The bug issue is closed, but a new issue is created to add a feature of parallel downloads in future releases.
