### ISSUE TITLE
Csv export for publication

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/open-MaStR#268]
Currently, two csv exports exist
1. exports db structure
2. exports joined tables by "Energieträger" but misses several relevant tables.

the following db tables are missing in the API export:

- additional_data_requested
- additional_locations_requested
- balancing_area
- basic_units
- electricity_consumer
- gas_consumer
- gas_producer
- gas_storage
- gas_storage_extended
- grids
- grid_connections
- market_actors
- market_roles

Think about good prefixes for exported tables.

**Comment by deniztepe** [comment]
The API export method is based on joins by technology. Most of the missing tables are not directly technology related. So, an extension of the `MaStRMirror.to_csv()` method for tables like grids raises some issues. The metadata is currently only working with technology related tables and had to be adapted. 

An option could be to fusion the two `to_csv` method so that technology related tables are joined and the rest is duplicated as in database. Would a folder with this structure make sense?

**Comment by chrwm** [comment]
We decided to integrate `MastrMirror.to_csv()` and `mastr.to_csv()`.
`mastr.to_csv()` will call  `MastrMirror.to_csv()` for exporting the joint technology tables. Besides `mastr.to_csv()` will export the tables above.

**Comment by deniztepe** [comment]
The method `mastr.to_csv()` is now exporting all tables as decided. The code is currently on the feature branch. @chrwm can you maybe test the results of export? Followings are to do until pull request: 

- [ ] Usage in main.py
- [ ] Documentation
- [ ] Unit tests

**Comment by chrwm** [comment]
Thanks for implementation, I'll test it later today!
