### ISSUE TITLE
Auto-versioning of csv folder

### ISSUE THREAD

**Issue by FlorianK13** [OpenEnergyPlatform/open-MaStR#317]
Right now the folder name is rli_v3.0.0
Is this hardcoded? When does the version number change? Can we also change from "rli" to "oep" to stress the community aspect?

**Comment by deniztepe** [comment]
The folder name is hard-coded as data version in `.open-MaStR\config\data.yml`

**Comment by chrwm** [comment]
The folder name is hardcoded in A=`open_mastr/utils/config/data.yml`. B=`.open-MaStR\config\data.yml` is then created with `open_mastr/utils/config.py`.
Since B is not updated when it already exists (and is used for creating the folder name), it does not reflect changes made in A. 
I'll put it on the agenda for later.
